
services:
  postgres:
    image: postgres:16
    container_name: warehouse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  service-api:
    build:
      context: ./service-api
    depends_on:
    - service-warehouse
    container_name: service-api
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: "8080"
      WAREHOUSE_URL: http://service-warehouse:9080
  service-warehouse:
    build:
      context: ./service-warehouse
    depends_on:
    - postgres
    container_name: service-warehouse
    ports:
      - "9080:9080"
    environment:
      HTTP_PORT: "9080"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: warehouse
volumes:
  postgres_data: