
services:
  postgres:
    image: postgres:16
    container_name: warehouse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      postgres
      -c
      wal_level=logical
  service-api:
    build:
      context: ./service-api
    depends_on:
    - service-warehouse
    container_name: service-api
    ports:
      - "8080:8080"
    environment:
      HTTP_PORT: "8080"
      WAREHOUSE_URL: http://service-warehouse:9080
  service-warehouse:
    build:
      context: ./service-warehouse
    depends_on:
    - postgres
    container_name: service-warehouse
    ports:
      - "9080:9080"
    environment:
      HTTP_PORT: "9080"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: warehouse
  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: quay.io/debezium/kafka:3.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      BROKER_ID: 1
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  connect:
    image: quay.io/debezium/connect:3.1
    container_name: connect
    depends_on:
      - kafka 
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" 
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  opensearch:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9600:9600"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "5601:5601"
  service-analytics:
    build:
      context: ./service-analytics
    container_name: service-analytics
    depends_on:
      kafka:
        condition: service_started
      rabbitmq:
        condition: service_started
      opensearch:
        condition: service_started
      register-connector:
        condition: service_completed_successfully
  register-connector:
    image: curlimages/curl:latest
    container_name: register-connector
    depends_on:
      - connect
    volumes:
      - ./docker/connectors:/connectors
    entrypoint: ["/bin/sh", "/connectors/register.sh"]
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  postgres_data: